# In this file we compare 2 implementations of PCA


# Get the data

In [1]:
from sklearn import datasets
import pandas as pd
data=datasets.load_breast_cancer()
X=pd.DataFrame(data['data'], columns=data['feature_names'])

In [2]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [3]:
from statsmodels.multivariate.pca import PCA

C:\Users\eldiy\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# PCA

In [5]:
pca=PCA(X,2) # selected 2 components
pca.scores.head()

comp_0    comp_1
0 -0.105747 -0.034242
1 -0.027467  0.066217
2 -0.065958  0.018894
3 -0.081937 -0.180569
4 -0.045269  0.034233

In [7]:
X.shape # originally we had 30 columns

(569, 30)

In [8]:
pca.rsquare #explained variance ratio (cumulative)

ncomp
0    0.000000
1    0.442720
2    0.632432
Name: rsquare, dtype: float64

In [12]:
pca.transformed_data #the data is standardized automatically

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [17]:
np.dot(X,pca.loadings) # transformed into PCA values

array([[-793.36467353,  772.38640049],
       [-831.37630426,  819.57303849],
       [-751.11180013,  737.92415565],
       ...,
       [-522.48686951,  512.14183299],
       [-801.86518972,  785.87263057],
       [-139.51959586,  132.51414967]])

In [28]:
pca.loadings # parameters used to transform the data

comp_0    comp_1
mean radius             -0.218902  0.233857
mean texture            -0.103725  0.059706
mean perimeter          -0.227537  0.215181
mean area               -0.220995  0.231077
mean smoothness         -0.142590 -0.186113
mean compactness        -0.239285 -0.151892
mean concavity          -0.258400 -0.060165
mean concave points     -0.260854  0.034768
mean symmetry           -0.138167 -0.190349
mean fractal dimension  -0.064363 -0.366575
radius error            -0.205979  0.105552
texture error           -0.017428 -0.089980
perimeter error         -0.211326  0.089457
area error              -0.202870  0.152293
smoothness error        -0.014531 -0.204430
compactness error       -0.170393 -0.232716
concavity error         -0.153590 -0.197207
concave points error    -0.183417 -0.130322
symmetry error          -0.042498 -0.183848
fractal dimension error -0.102568 -0.280092
worst radius            -0.227997  0.219866
worst texture           -0.104469  0.045467
worst perimeter         -0.236640  0.199878
worst area              -0.224871  0.219352
worst smoothness        -0.127953 -0.172304
worst compactness       -0.210096 -0.143593
worst concavity         -0.228768 -0.097964
worst concave points    -0.250886  0.008257
worst symmetry          -0.122905 -0.141883
worst fractal dimension -0.131784 -0.275339

In [30]:
pca.projection 
#revertion of PCA back into actual values. We can see that values are not exactly the same. 
#That happened because we used only 2 parameters. The more parameters used, the higher the precision. 

mean radius  mean texture  mean perimeter    mean area  mean smoothness  \
0      19.608160     22.887228      132.571275  1210.881235         0.119875   
1      19.070388     21.320774      124.844676  1146.583373         0.091290   
2      19.431960     22.121283      129.260248  1187.784767         0.105037   
3      11.156356     19.828138       77.636067   373.495458         0.137505   
4      18.764446     21.543555      123.884796  1118.949714         0.099151   
..           ...           ...             ...          ...              ...   
564    22.035510     23.077563      146.225843  1445.850594         0.099908   
565    20.002124     21.900044      131.647312  1240.841406         0.094588   
566    16.661835     20.337643      108.846019   907.055037         0.093902   
567    20.746877     23.485024      140.545324  1325.193634         0.121520   
568    10.459479     17.021230       65.226908   283.934566         0.083636   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            0.236029        0.287340             0.139260       0.226111   
1            0.104289        0.119886             0.078146       0.170552   
2            0.168121        0.201659             0.108355       0.197256   
3            0.276633        0.284643             0.107103       0.261692   
4            0.138416        0.160458             0.091343       0.185898   
..                ...             ...                  ...            ...   
564          0.156978        0.204190             0.118861       0.186883   
565          0.123512        0.149698             0.092112       0.176832   
566          0.104955        0.105537             0.064187       0.175998   
567          0.248736        0.310341             0.151585       0.229142   
568          0.029834       -0.027103            -0.005548       0.156945   

     mean fractal dimension  ...  worst radius  worst texture  \
0                  0.072010  ...     24.321573      31.030652   
1                  0.054138  ...     22.898938      28.261176   
2                  0.062621  ...     23.723723      29.655892   
3                  0.092603  ...     13.201586      27.377791   
4                  0.059547  ...     22.670266      28.745758   
..                      ...  ...           ...            ...   
564                0.056472  ...     27.156463      30.806919   
565                0.055252  ...     24.250984      29.111490   
566                0.058449  ...     19.671967      27.014238   
567                0.071832  ...     25.916548      31.866136   
568                0.058578  ...     10.953017      22.351933   

     worst perimeter   worst area  worst smoothness  worst compactness  \
0         167.219580  1813.378475          0.166861           0.601859   
1         151.517979  1656.219897          0.124527           0.248069   
2         160.030297  1748.217608          0.144879           0.419367   
3          94.896436   509.559425          0.193550           0.721459   
4         151.598595  1627.063078          0.136198           0.340262   
..               ...          ...               ...                ...   
564       182.421971  2150.608563          0.137105           0.386196   
565       161.449335  1813.045509          0.129353           0.298647   
566       130.006583  1278.640448          0.128558           0.252813   
567       178.465829  1999.084025          0.169224           0.634652   
568        68.262344   263.877051          0.113751           0.058298   

     worst concavity  worst concave points  worst symmetry  \
0           0.750334              0.265018        0.377004   
1           0.309105              0.155993        0.275168   
2           0.523652              0.209666        0.324207   
3           0.821668              0.226398        0.434309   
4           0.420062              0.180504        0.302887   
..               ...                   ...             ...   
564         0.5

# Comparison with sklearn PCA

In [20]:
from sklearn.decomposition import PCA

In [32]:
pca1=PCA(2) # you can specify explained variance ratio instead of number of components

In [33]:
pca1.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [35]:
pca1.explained_variance_ratio_ # we can see the difference. But it is simply because the data is not standardized

array([0.98204467, 0.01617649])

In [36]:
pca1.transform(X) #therefore data is different

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X1 = pd.DataFrame(scaler.transform(X),columns=X.columns.values.tolist())

In [38]:
pca1=PCA(2)
pca1.fit(X1)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [40]:
pca1.explained_variance_ratio_.sum() # after standartization we obtain 100% the same result

0.6324320765155951

In [41]:
pca1.transform(X) # here as well

array([[ 793.36467353, -772.38640049],
       [ 831.37630426, -819.57303849],
       [ 751.11180013, -737.92415566],
       ...,
       [ 522.48686951, -512.14183299],
       [ 801.86518972, -785.87263057],
       [ 139.51959586, -132.51414967]])

In [45]:
pca_inv=pca1.inverse_transform(pca1.transform(X1)) # inverse transformation of pca will lead to standardized values

In [49]:
pd.DataFrame(scaler.inverse_transform(pca_inv), columns=X.columns) #Dataframe of inverse transformation of scaling

mean radius  mean texture  mean perimeter    mean area  mean smoothness  \
0      19.608160     22.887228      132.571275  1210.881235         0.119875   
1      19.070388     21.320774      124.844676  1146.583373         0.091290   
2      19.431960     22.121283      129.260248  1187.784767         0.105037   
3      11.156356     19.828138       77.636067   373.495458         0.137505   
4      18.764446     21.543555      123.884796  1118.949714         0.099151   
..           ...           ...             ...          ...              ...   
564    22.035510     23.077563      146.225843  1445.850594         0.099908   
565    20.002124     21.900044      131.647312  1240.841406         0.094588   
566    16.661835     20.337643      108.846019   907.055037         0.093902   
567    20.746877     23.485024      140.545324  1325.193634         0.121520   
568    10.459479     17.021230       65.226908   283.934566         0.083636   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            0.236029        0.287340             0.139260       0.226111   
1            0.104289        0.119886             0.078146       0.170552   
2            0.168121        0.201659             0.108355       0.197256   
3            0.276633        0.284643             0.107103       0.261692   
4            0.138416        0.160458             0.091343       0.185898   
..                ...             ...                  ...            ...   
564          0.156978        0.204190             0.118861       0.186883   
565          0.123512        0.149698             0.092112       0.176832   
566          0.104955        0.105537             0.064187       0.175998   
567          0.248736        0.310341             0.151585       0.229142   
568          0.029834       -0.027103            -0.005548       0.156945   

     mean fractal dimension  ...  worst radius  worst texture  \
0                  0.072010  ...     24.321573      31.030652   
1                  0.054138  ...     22.898938      28.261176   
2                  0.062621  ...     23.723723      29.655892   
3                  0.092603  ...     13.201586      27.377791   
4                  0.059547  ...     22.670266      28.745758   
..                      ...  ...           ...            ...   
564                0.056472  ...     27.156463      30.806919   
565                0.055252  ...     24.250984      29.111490   
566                0.058449  ...     19.671967      27.014238   
567                0.071832  ...     25.916548      31.866136   
568                0.058578  ...     10.953017      22.351933   

     worst perimeter   worst area  worst smoothness  worst compactness  \
0         167.219580  1813.378475          0.166861           0.601859   
1         151.517979  1656.219897          0.124527           0.248069   
2         160.030297  1748.217608          0.144879           0.419367   
3          94.896436   509.559425          0.193550           0.721459   
4         151.598595  1627.063078          0.136198           0.340262   
..               ...          ...               ...                ...   
564       182.421971  2150.608563          0.137105           0.386196   
565       161.449335  1813.045509          0.129353           0.298647   
566       130.006583  1278.640448          0.128558           0.252813   
567       178.465829  1999.084025          0.169224           0.634652   
568        68.262344   263.877051          0.113751           0.058298   

     worst concavity  worst concave points  worst symmetry  \
0           0.750334              0.265018        0.377004   
1           0.309105              0.155993        0.275168   
2           0.523652              0.209666        0.324207   
3           0.821668              0.226398        0.434309   
4           0.420062              0.180504        0.302887   
..               ...                   ...             ...   
564         0.5

# Conclusion

Statsmodels PCA implementation has a few advantages:
1. Data is standardized by itself
2. No need of fitting data. Everything is calculated on the initialisation step
3. Inverse calculations are also omitted - you simply call invere transformation function and it gives you inverse transformation both for PCA and for standartisation.
4. Returns you pandas DataFrame object keeping all the names.

But at the same time sklearn implementation has following pros:
1. You can specify the explained variance ratio instead of number of components
2. If you already standardized your data, you don't need to specify that (we didn't see it here, but in statsmodels you need to define that you already have standardized your data)
3. Structure follows sklearn structure that simplifies the process (you know that first you create the object, then you fit it and so on)

In terms of scientifical importance, statsmodels approach is much more powerfull, since it proposes you different approaches of PC calculation (both analytical and numerical), while sklearn one is optimized for production.