In [29]:
puzzle = [[5,3,0,0,7,0,0,0,0],
          [6,0,0,1,9,5,0,0,0],
          [0,9,8,0,0,0,0,6,0],
          [8,0,0,0,6,0,0,0,3],
          [4,0,0,8,0,3,0,0,1],
          [7,0,0,0,2,0,0,0,6],
          [0,6,0,0,0,0,2,8,0],
          [0,0,0,4,1,9,0,0,5],
          [0,0,0,0,8,0,0,7,9]]

solution = [[5,3,4,6,7,8,9,1,2],
            [6,7,2,1,9,5,3,4,8],
            [1,9,8,3,4,2,5,6,7],
            [8,5,9,7,6,1,4,2,3],
            [4,2,6,8,5,3,7,9,1],
            [7,1,3,9,2,4,8,5,6],
            [9,6,1,5,3,7,2,8,4],
            [2,8,7,4,1,9,6,3,5],
            [3,4,5,2,8,6,1,7,9]]


import numpy as np

a=np.array(puzzle)
solution = np.array(solution)

In [2]:
a.sum(axis=1)

array([15, 21, 23, 17, 16, 15, 16, 19, 24])

In [3]:
boxes=a.reshape((3,3,-1)).transpose((0,2,1)).reshape((3,3,3,3))

In [4]:
exists = {i:list(a.ravel()).count(i) for i in a.ravel() if i!=0}

In [5]:
required = {i: 9-j for i,j in exists.items()}

In [6]:
[[i]*j for i,j in required.items()]

[[5, 5, 5, 5, 5, 5],
 [3, 3, 3, 3, 3, 3],
 [7, 7, 7, 7, 7, 7],
 [6, 6, 6, 6],
 [1, 1, 1, 1, 1, 1],
 [9, 9, 9, 9, 9],
 [8, 8, 8, 8],
 [4, 4, 4, 4, 4, 4, 4],
 [2, 2, 2, 2, 2, 2, 2]]

In [78]:
required = [[list(set(list(range(10)))-{k for k in j.ravel()}) for j in i]for i in boxes]

In [79]:
required

[[[1, 2, 4, 7], [2, 3, 4, 6, 8], [1, 2, 3, 4, 5, 7, 8, 9]],
 [[1, 2, 3, 5, 6, 9], [1, 4, 5, 7, 9], [2, 4, 5, 7, 8, 9]],
 [[1, 2, 3, 4, 5, 7, 8, 9], [2, 3, 5, 6, 7], [1, 3, 4, 6]]]

In [60]:
import random

In [16]:
columns = boxes.sum(axis=3).sum(axis=0).ravel()
rows = boxes.sum(axis=1).sum(axis=1).ravel()
rows

array([15, 21, 23, 17, 16, 15, 16, 19, 24])

In [28]:
(rows==45).any()

False

In [44]:
boxes.sum(axis=3).sum(axis=2)

array([[31, 22,  6],
       [19, 19, 10],
       [ 6, 22, 31]])

In [47]:
def test(a):
    boxes=a.reshape((3,3,-1)).transpose((0,2,1)).reshape((3,3,3,3))
    columns = boxes.sum(axis=3).sum(axis=0).ravel()
    rows = boxes.sum(axis=1).sum(axis=1).ravel()
    sboxes = boxes.sum(axis=3).sum(axis=2)
    test1 = (rows==45).all()
    test2 = (columns==45).all()
    test3 = (sboxes==45).all()
    return test1 and test2 and test3

In [49]:
test(a)

False

In [91]:
dct={i:{j:[]for j in range(3)} for i in range(3)}
dct

{0: {0: [], 1: [], 2: []}, 1: {0: [], 1: [], 2: []}, 2: {0: [], 1: [], 2: []}}

In [92]:
final = []
for ix1,i in enumerate(boxes):
    final.append([])
    for ix2,j in enumerate(i):        
        original = j.ravel()
        new = required[ix1][ix2].copy()
        random.shuffle(new)
        new1=new.copy()
        while True:
            print(new)
            if new not in dct[ix1][ix2]:
                dct[ix1][ix2].append(new1)
                print(dct)
                break
        #print('doo')
        fixed = [i if i else new.pop() for i in original]
        #print('boo')
        final[ix1].append(fixed)
        print('box',ix1,ix2,'is finished')
        


[1, 2, 4, 7]
{0: {0: [[1, 2, 4, 7]], 1: [], 2: []}, 1: {0: [], 1: [], 2: []}, 2: {0: [], 1: [], 2: []}}
box 0 0 is finished
[8, 6, 4, 2, 3]
{0: {0: [[1, 2, 4, 7]], 1: [[8, 6, 4, 2, 3]], 2: []}, 1: {0: [], 1: [], 2: []}, 2: {0: [], 1: [], 2: []}}
box 0 1 is finished
[1, 7, 8, 4, 5, 9, 3, 2]
{0: {0: [[1, 2, 4, 7]], 1: [[8, 6, 4, 2, 3]], 2: [[1, 7, 8, 4, 5, 9, 3, 2]]}, 1: {0: [], 1: [], 2: []}, 2: {0: [], 1: [], 2: []}}
box 0 2 is finished
[9, 3, 6, 5, 1, 2]
{0: {0: [[1, 2, 4, 7]], 1: [[8, 6, 4, 2, 3]], 2: [[1, 7, 8, 4, 5, 9, 3, 2]]}, 1: {0: [[9, 3, 6, 5, 1, 2]], 1: [], 2: []}, 2: {0: [], 1: [], 2: []}}
box 1 0 is finished
[7, 5, 4, 1, 9]
{0: {0: [[1, 2, 4, 7]], 1: [[8, 6, 4, 2, 3]], 2: [[1, 7, 8, 4, 5, 9, 3, 2]]}, 1: {0: [[9, 3, 6, 5, 1, 2]], 1: [[7, 5, 4, 1, 9]], 2: []}, 2: {0: [], 1: [], 2: []}}
box 1 1 is finished
[7, 9, 2, 4, 8, 5]
{0: {0: [[1, 2, 4, 7]], 1: [[8, 6, 4, 2, 3]], 2: [[1, 7, 8, 4, 5, 9, 3, 2]]}, 1: {0: [[9, 3, 6, 5, 1, 2]], 1: [[7, 5, 4, 1, 9]], 2: [[7, 9, 2, 4, 8, 5]]},

In [86]:
required

[[[1, 2, 4, 7], [2, 3, 4, 6, 8], [1, 2, 3, 4, 5, 7, 8, 9]],
 [[1, 2, 3, 5, 6, 9], [1, 4, 5, 7, 9], [2, 4, 5, 7, 8, 9]],
 [[1, 2, 3, 4, 5, 7, 8, 9], [2, 3, 5, 6, 7], [1, 3, 4, 6]]]

In [108]:
a.reshape((3,3,-1)).transpose((0,2,1)).reshape((3,3,3,3));


In [111]:
boxes

array([[[[5, 6, 0],
         [3, 0, 9],
         [0, 0, 8]],

        [[0, 1, 0],
         [7, 9, 0],
         [0, 5, 0]],

        [[0, 0, 0],
         [0, 0, 6],
         [0, 0, 0]]],


       [[[8, 4, 7],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 8, 0],
         [6, 0, 2],
         [0, 3, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [3, 1, 6]]],


       [[[0, 0, 0],
         [6, 0, 0],
         [0, 0, 0]],

        [[0, 4, 0],
         [0, 1, 8],
         [0, 9, 0]],

        [[2, 0, 0],
         [8, 0, 7],
         [0, 5, 9]]]])

In [132]:
solution = np.array(final).reshape(3,3,-1).transpose((0,1,2)).reshape((3,3,3,3)).transpose((0,3,1,2)).reshape(3,3,-1).reshape((9,9))

In [133]:
test(solution)

False

In [150]:
dct={i:{j:[]for j in range(3)} for i in range(3)}
def attempt(arr):
    boxes=a.reshape((3,3,-1)).transpose((0,2,1)).reshape((3,3,3,3))
    final = []
    for ix1,i in enumerate(boxes):
        final.append([])
        for ix2,j in enumerate(i):        
            original = j.ravel()
            new = required[ix1][ix2].copy()
            random.shuffle(new)
            new1=new.copy()
            dct[ix1][ix2].append(new1)
            
            fixed = [i if i else new.pop() for i in original]
            final[ix1].append(fixed)
    solution = np.array(final).reshape(3,3,-1).transpose((0,1,2)).reshape((3,3,3,3)).transpose((0,3,1,2)).reshape(3,3,-1).reshape((9,9))
    return solution



In [151]:
solution = a.copy()
k=0
while not test(solution):
    solution = attempt(a)
    k+=1
    print(k)
print(solution)


2262140
2262141
2262142
2262143
2262144
2262145
2262146
2262147
2262148
2262149
2262150
2262151
2262152
2262153
2262154
2262155
2262156
2262157
2262158
2262159
2262160
2262161
2262162
2262163
2262164
2262165
2262166
2262167
2262168
2262169
2262170
2262171
2262172
2262173
2262174
2262175
2262176
2262177
2262178
2262179
2262180
2262181
2262182
2262183
2262184
2262185
2262186
2262187
2262188
2262189
2262190
2262191
2262192
2262193
2262194
2262195
2262196
2262197
2262198
2262199
2262200
2262201
2262202
2262203
2262204
2262205
2262206
2262207
2262208
2262209
2262210
2262211
2262212
2262213
2262214
2262215
2262216
2262217
2262218
2262219
2262220
2262221
2262222
2262223
2262224
2262225
2262226
2262227
2262228
2262229
2262230
2262231
2262232
2262233
2262234
2262235
2262236
2262237
2262238
2262239
2262240
2262241
2262242
2262243
2262244
2262245
2262246
2262247
2262248
2262249
2262250
2262251
2262252
2262253
2262254
2262255
2262256
2262257
2262258
2262259
2262260
2262261
2262262
2262263
2262264

KeyboardInterrupt: 

In [152]:
dct

  [5, 7, 6, 2, 3],
   [6, 3, 2, 7, 5],
   [3, 2, 7, 5, 6],
   [5, 7, 3, 2, 6],
   [6, 3, 7, 2, 5],
   [5, 2, 3, 7, 6],
   [6, 3, 7, 5, 2],
   [7, 3, 5, 6, 2],
   [7, 5, 6, 3, 2],
   [6, 5, 3, 7, 2],
   [3, 5, 7, 2, 6],
   [6, 2, 7, 3, 5],
   [2, 7, 5, 6, 3],
   [2, 7, 3, 5, 6],
   [5, 2, 6, 3, 7],
   [3, 7, 6, 5, 2],
   [3, 2, 7, 6, 5],
   [6, 7, 5, 3, 2],
   [6, 5, 7, 3, 2],
   [5, 3, 6, 7, 2],
   [3, 2, 5, 6, 7],
   [7, 2, 6, 3, 5],
   [3, 6, 2, 5, 7],
   [5, 7, 3, 6, 2],
   [6, 7, 3, 2, 5],
   [6, 5, 3, 2, 7],
   [5, 6, 7, 2, 3],
   [6, 5, 2, 7, 3],
   [7, 2, 5, 6, 3],
   [2, 7, 3, 6, 5],
   [7, 6, 3, 2, 5],
   [6, 2, 7, 5, 3],
   [2, 7, 5, 6, 3],
   [5, 7, 3, 6, 2],
   [5, 6, 3, 2, 7],
   [3, 5, 2, 7, 6],
   [3, 7, 2, 5, 6],
   [6, 3, 7, 5, 2],
   [5, 7, 6, 3, 2],
   [6, 2, 5, 3, 7],
   [7, 6, 2, 5, 3],
   [2, 7, 5, 3, 6],
   [2, 7, 6, 5, 3],
   [6, 2, 5, 7, 3],
   [6, 3, 2, 5, 7],
   [5, 2, 3, 7, 6],
   [6, 7, 5, 2, 3],
   [6, 3, 5, 2, 7],
   [6, 7, 3, 2, 5],
   [2, 5, 3, 6, 7],
 